spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abuzar-cpu/micro_config
          search-paths: eureka-server, licensing-service, organization-service
#        native:
#          search-locations: file:\\\home\abuzar\Desktop\IdeaProjects\micro_config

server:
  port: 8071

# in case you want to encrypt sensitive properties which you will do in production likely
#encrypt:
#  key: secret
  # Symmetric key value