#stage 1
# Starting with base image that contains java runtime
FROM openjdk:latest as build

# Adding maintainer info
LABEL maintainer="Abuzar Karimzada <kerimovabuzer25@gmail.com>"

# The application's jar file
ARG JAR_FILE=target/*.jar

# Adding the jar file to container
COPY ${JAR_FILE} app.jar

# Unpackaging jar file
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf /app.jar)

# Stage 2
# Taking the same java runtime
FROM openjdk:latest

# Add volume pointing to /tmp
VOLUME /tmp

# Copy unpackaged application to new container
ARG DEPENDENCY=/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

# Executing the application
ENTRYPOINT ["java", "-cp", "app:app/lib/*", "az.yelo.eurekaserver.EurekaserverApplication"]